// <auto-generated />
using System;
using DarlingDb;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DarlingNet.Migrations
{
    [DbContext(typeof(db))]
    [Migration("20220519133402_UpdateNew1905")]
    partial class UpdateNew1905
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0-preview.5.21301.9");

            modelBuilder.Entity("DarlingDb.Models.ButtonClick", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("ChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Counter")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("MessageId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RoleDelOrGet")
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("RoleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId");

                    b.HasIndex("RoleId");

                    b.ToTable("ButtonClick");
                });

            modelBuilder.Entity("DarlingDb.Models.Captcha", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("Result")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TimeToClear")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GuildId");

                    b.ToTable("Captcha");
                });

            modelBuilder.Entity("DarlingDb.Models.Channel", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BadWordString")
                        .HasColumnType("TEXT");

                    b.Property<bool>("DelCaps")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DelUrl")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DelUrlImage")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("GiveXP")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("GuildsId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("InviteMessage")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SendBadWord")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Spaming")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseAdminCommand")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseCommand")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseRPcommand")
                        .HasColumnType("INTEGER");

                    b.Property<string>("csUrlWhiteListString")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GuildsId");

                    b.ToTable("Channels");
                });

            modelBuilder.Entity("DarlingDb.Models.DarlingBoost", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Ends")
                        .HasColumnType("TEXT");

                    b.Property<ushort>("Streak")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("UsersId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UsersId")
                        .IsUnique();

                    b.ToTable("DarlingBoost");
                });

            modelBuilder.Entity("DarlingDb.Models.EmoteClick", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("ChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Emote")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Get")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("MessageId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId");

                    b.HasIndex("RoleId");

                    b.ToTable("EmoteClick");
                });

            modelBuilder.Entity("DarlingDb.Models.Feedback", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdminMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .HasColumnType("TEXT");

                    b.Property<byte>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Time")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Feedback");
                });

            modelBuilder.Entity("DarlingDb.Models.GiveAways", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("ChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Surpice")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Times")
                        .HasColumnType("TEXT");

                    b.Property<uint>("WinnerCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId");

                    b.ToTable("GiveAways");
                });

            modelBuilder.Entity("DarlingDb.Models.Guilds", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CommandInviseString")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Leaved")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Prefix")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("PrivateId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("VS")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VoiceAndCategoryChannelString")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Guilds");
                });

            modelBuilder.Entity("DarlingDb.Models.Guilds_Captcha", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("ChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("RoleId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Run")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId")
                        .IsUnique();

                    b.HasIndex("GuildId")
                        .IsUnique();

                    b.HasIndex("RoleId")
                        .IsUnique();

                    b.ToTable("Guilds_Captcha");
                });

            modelBuilder.Entity("DarlingDb.Models.Guilds_Logs", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("ChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId");

                    b.ToTable("Guilds_Logs");
                });

            modelBuilder.Entity("DarlingDb.Models.Guilds_Meeting_Leave", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("GuildsId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("LeaveChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LeaveMessage")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GuildsId")
                        .IsUnique();

                    b.HasIndex("LeaveChannelId")
                        .IsUnique();

                    b.ToTable("Guilds_Meeting_Leave");
                });

            modelBuilder.Entity("DarlingDb.Models.Guilds_Meeting_Welcome", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("GuildsId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("WelcomeChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WelcomeDMmessage")
                        .HasColumnType("TEXT");

                    b.Property<bool>("WelcomeDMuser")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WelcomeMessage")
                        .HasColumnType("TEXT");

                    b.Property<ulong?>("WelcomeRoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GuildsId")
                        .IsUnique();

                    b.HasIndex("WelcomeChannelId")
                        .IsUnique();

                    b.HasIndex("WelcomeRoleId")
                        .IsUnique();

                    b.ToTable("Guilds_Meeting_Welcome");
                });

            modelBuilder.Entity("DarlingDb.Models.Guilds_Raid", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("GuildsId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RaidMuted")
                        .HasColumnType("TEXT");

                    b.Property<bool>("RaidRunning")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("RaidTime")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("RaidUserCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GuildsId")
                        .IsUnique();

                    b.ToTable("Guilds_Raid");
                });

            modelBuilder.Entity("DarlingDb.Models.Guilds_Warns", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte>("CountWarn")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("GuildsId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("ReportTypes")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("Time")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GuildsId");

                    b.ToTable("Guilds_Warns");
                });

            modelBuilder.Entity("DarlingDb.Models.Invites", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("ChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<uint>("Users_GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsesCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId");

                    b.HasIndex("Users_GuildId");

                    b.ToTable("Invites");
                });

            modelBuilder.Entity("DarlingDb.Models.Pet.Items", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Emoji")
                        .HasColumnType("TEXT");

                    b.Property<byte>("ItemType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("PetsId")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("Price")
                        .HasColumnType("INTEGER");

                    b.Property<sbyte>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PetsId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("DarlingDb.Models.Pets", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Die")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("EAT")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastEat")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastMood")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSleep")
                        .HasColumnType("TEXT");

                    b.Property<byte>("MOOD")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<byte>("PetType")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RegenController")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("SLEEP")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SleepNow")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("XP")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Pets");
                });

            modelBuilder.Entity("DarlingDb.Models.PrivateChannels", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<uint>("Users_GuildId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Users_GuildId")
                        .IsUnique();

                    b.ToTable("PrivateChannels");
                });

            modelBuilder.Entity("DarlingDb.Models.ReportSystem.Reports", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("GuildsId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Rules")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GuildsId");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("DarlingDb.Models.ReportSystem.Reports_Punishes", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("ReportId")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("TimeReport")
                        .HasColumnType("TEXT");

                    b.Property<byte>("TypeReport")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ReportId");

                    b.ToTable("Reports_Punishes");
                });

            modelBuilder.Entity("DarlingDb.Models.Roles", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("RoleId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("DarlingDb.Models.Roles_Timer", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("RoleId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ToTime")
                        .HasColumnType("TEXT");

                    b.Property<uint>("Users_GuildId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("Users_GuildId");

                    b.ToTable("Roles_Timer");
                });

            modelBuilder.Entity("DarlingDb.Models.Tasks", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("ChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Repeat")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Times")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("DarlingDb.Models.TempUser", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Reason")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ToTime")
                        .HasColumnType("TEXT");

                    b.Property<uint>("Users_GuildId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Users_GuildId");

                    b.ToTable("TempUser");
                });

            modelBuilder.Entity("DarlingDb.Models.Users", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<ushort>("BirthDateComplete")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BlockedReason")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBot")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastOnline")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastReputation")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("LastReputationUserId")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("RealCoin")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("Reputation")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("StingerRulesAccept")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DarlingDb.Models.Users_Guild", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("BirthDateInvise")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("CountWarns")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Daily")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("GuildsId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Leaved")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReportedRules")
                        .HasColumnType("TEXT");

                    b.Property<ushort>("Streak")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("UsersId")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("UsersMId")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("VoiceActive")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("XP")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("ZeroCoin")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GuildsId");

                    b.HasIndex("UsersId");

                    b.HasIndex("UsersMId");

                    b.ToTable("Users_Guild");
                });

            modelBuilder.Entity("DarlingDb.QiwiTransactions", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("discord_id")
                        .HasColumnType("INTEGER");

                    b.Property<double>("invoice_ammount")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("invoice_date_add")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("QiwiTransactions");
                });

            modelBuilder.Entity("DarlingDb.Role", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("GuildsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GuildsId");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("Reports_PunishesUsers_Guild", b =>
                {
                    b.Property<ulong>("Reports_PunishesId")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("Users_GuildId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Reports_PunishesId", "Users_GuildId");

                    b.HasIndex("Users_GuildId");

                    b.ToTable("Reports_PunishesUsers_Guild");
                });

            modelBuilder.Entity("DarlingDb.Models.ButtonClick", b =>
                {
                    b.HasOne("DarlingDb.Models.Channel", "Channel")
                        .WithMany("ButtonClick")
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DarlingDb.Role", "Role")
                        .WithMany("ButtonClick")
                        .HasForeignKey("RoleId");

                    b.Navigation("Channel");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("DarlingDb.Models.Captcha", b =>
                {
                    b.HasOne("DarlingDb.Models.Guilds", "Guild")
                        .WithMany("Captcha")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("DarlingDb.Models.Channel", b =>
                {
                    b.HasOne("DarlingDb.Models.Guilds", "Guilds")
                        .WithMany("Channels")
                        .HasForeignKey("GuildsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guilds");
                });

            modelBuilder.Entity("DarlingDb.Models.DarlingBoost", b =>
                {
                    b.HasOne("DarlingDb.Models.Users", "Users")
                        .WithOne("Boost")
                        .HasForeignKey("DarlingDb.Models.DarlingBoost", "UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Users");
                });

            modelBuilder.Entity("DarlingDb.Models.EmoteClick", b =>
                {
                    b.HasOne("DarlingDb.Models.Channel", "Channel")
                        .WithMany("EmoteClick")
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DarlingDb.Role", "Role")
                        .WithMany("EmoteClick")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Channel");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("DarlingDb.Models.Feedback", b =>
                {
                    b.HasOne("DarlingDb.Models.Users", "User")
                        .WithMany("Feedback")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DarlingDb.Models.GiveAways", b =>
                {
                    b.HasOne("DarlingDb.Models.Channel", "Channel")
                        .WithMany("GiveAways")
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Channel");
                });

            modelBuilder.Entity("DarlingDb.Models.Guilds_Captcha", b =>
                {
                    b.HasOne("DarlingDb.Models.Channel", "Channel")
                        .WithOne("Guilds_Captcha")
                        .HasForeignKey("DarlingDb.Models.Guilds_Captcha", "ChannelId");

                    b.HasOne("DarlingDb.Models.Guilds", "Guild")
                        .WithOne("Guilds_Captcha")
                        .HasForeignKey("DarlingDb.Models.Guilds_Captcha", "GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DarlingDb.Role", "Role")
                        .WithOne("Guilds_Captcha")
                        .HasForeignKey("DarlingDb.Models.Guilds_Captcha", "RoleId");

                    b.Navigation("Channel");

                    b.Navigation("Guild");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("DarlingDb.Models.Guilds_Logs", b =>
                {
                    b.HasOne("DarlingDb.Models.Channel", "Channel")
                        .WithMany("Guilds_Logs")
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Channel");
                });

            modelBuilder.Entity("DarlingDb.Models.Guilds_Meeting_Leave", b =>
                {
                    b.HasOne("DarlingDb.Models.Guilds", "Guilds")
                        .WithOne("Guilds_Meeting_Leave")
                        .HasForeignKey("DarlingDb.Models.Guilds_Meeting_Leave", "GuildsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DarlingDb.Models.Channel", "LeaveChannel")
                        .WithOne("Guilds_Meeting_Leave")
                        .HasForeignKey("DarlingDb.Models.Guilds_Meeting_Leave", "LeaveChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guilds");

                    b.Navigation("LeaveChannel");
                });

            modelBuilder.Entity("DarlingDb.Models.Guilds_Meeting_Welcome", b =>
                {
                    b.HasOne("DarlingDb.Models.Guilds", "Guilds")
                        .WithOne("Guilds_Meeting_Welcome")
                        .HasForeignKey("DarlingDb.Models.Guilds_Meeting_Welcome", "GuildsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DarlingDb.Models.Channel", "WelcomeChannel")
                        .WithOne("Guilds_Meeting_Welcome")
                        .HasForeignKey("DarlingDb.Models.Guilds_Meeting_Welcome", "WelcomeChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DarlingDb.Role", "WelcomeRole")
                        .WithOne("Guilds_Meeting_Welcome")
                        .HasForeignKey("DarlingDb.Models.Guilds_Meeting_Welcome", "WelcomeRoleId");

                    b.Navigation("Guilds");

                    b.Navigation("WelcomeChannel");

                    b.Navigation("WelcomeRole");
                });

            modelBuilder.Entity("DarlingDb.Models.Guilds_Raid", b =>
                {
                    b.HasOne("DarlingDb.Models.Guilds", "Guilds")
                        .WithOne("Guilds_Raid")
                        .HasForeignKey("DarlingDb.Models.Guilds_Raid", "GuildsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guilds");
                });

            modelBuilder.Entity("DarlingDb.Models.Guilds_Warns", b =>
                {
                    b.HasOne("DarlingDb.Models.Guilds", "Guilds")
                        .WithMany("Guilds_Warns")
                        .HasForeignKey("GuildsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guilds");
                });

            modelBuilder.Entity("DarlingDb.Models.Invites", b =>
                {
                    b.HasOne("DarlingDb.Models.Channel", "Channel")
                        .WithMany("Invites")
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DarlingDb.Models.Users_Guild", "Users_Guild")
                        .WithMany("Invites")
                        .HasForeignKey("Users_GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Channel");

                    b.Navigation("Users_Guild");
                });

            modelBuilder.Entity("DarlingDb.Models.Pet.Items", b =>
                {
                    b.HasOne("DarlingDb.Models.Pets", "Pets")
                        .WithMany("Items")
                        .HasForeignKey("PetsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pets");
                });

            modelBuilder.Entity("DarlingDb.Models.Pets", b =>
                {
                    b.HasOne("DarlingDb.Models.Users", "User")
                        .WithOne("Pet")
                        .HasForeignKey("DarlingDb.Models.Pets", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DarlingDb.Models.PrivateChannels", b =>
                {
                    b.HasOne("DarlingDb.Models.Users_Guild", "Users_Guild")
                        .WithOne("PrivateChannels")
                        .HasForeignKey("DarlingDb.Models.PrivateChannels", "Users_GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Users_Guild");
                });

            modelBuilder.Entity("DarlingDb.Models.ReportSystem.Reports", b =>
                {
                    b.HasOne("DarlingDb.Models.Guilds", "Guilds")
                        .WithMany("Reports")
                        .HasForeignKey("GuildsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guilds");
                });

            modelBuilder.Entity("DarlingDb.Models.ReportSystem.Reports_Punishes", b =>
                {
                    b.HasOne("DarlingDb.Models.ReportSystem.Reports", "Report")
                        .WithMany("ReportsList")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("DarlingDb.Models.Roles", b =>
                {
                    b.HasOne("DarlingDb.Role", "Role")
                        .WithMany("Roles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("DarlingDb.Models.Roles_Timer", b =>
                {
                    b.HasOne("DarlingDb.Role", "Role")
                        .WithMany("Roles_Timer")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DarlingDb.Models.Users_Guild", "Users_Guild")
                        .WithMany("Roles_Timer")
                        .HasForeignKey("Users_GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("Users_Guild");
                });

            modelBuilder.Entity("DarlingDb.Models.Tasks", b =>
                {
                    b.HasOne("DarlingDb.Models.Channel", "Channel")
                        .WithMany("Tasks")
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Channel");
                });

            modelBuilder.Entity("DarlingDb.Models.TempUser", b =>
                {
                    b.HasOne("DarlingDb.Models.Users_Guild", "Users_Guild")
                        .WithMany("TempUser")
                        .HasForeignKey("Users_GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Users_Guild");
                });

            modelBuilder.Entity("DarlingDb.Models.Users_Guild", b =>
                {
                    b.HasOne("DarlingDb.Models.Guilds", "Guilds")
                        .WithMany("Users_Guild")
                        .HasForeignKey("GuildsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DarlingDb.Models.Users", "Users")
                        .WithMany("Users_Guild")
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DarlingDb.Models.Users_Guild", "UsersM")
                        .WithMany()
                        .HasForeignKey("UsersMId");

                    b.Navigation("Guilds");

                    b.Navigation("Users");

                    b.Navigation("UsersM");
                });

            modelBuilder.Entity("DarlingDb.Role", b =>
                {
                    b.HasOne("DarlingDb.Models.Guilds", "Guilds")
                        .WithMany("Role")
                        .HasForeignKey("GuildsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guilds");
                });

            modelBuilder.Entity("Reports_PunishesUsers_Guild", b =>
                {
                    b.HasOne("DarlingDb.Models.ReportSystem.Reports_Punishes", null)
                        .WithMany()
                        .HasForeignKey("Reports_PunishesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DarlingDb.Models.Users_Guild", null)
                        .WithMany()
                        .HasForeignKey("Users_GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DarlingDb.Models.Channel", b =>
                {
                    b.Navigation("ButtonClick");

                    b.Navigation("EmoteClick");

                    b.Navigation("GiveAways");

                    b.Navigation("Guilds_Captcha");

                    b.Navigation("Guilds_Logs");

                    b.Navigation("Guilds_Meeting_Leave");

                    b.Navigation("Guilds_Meeting_Welcome");

                    b.Navigation("Invites");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("DarlingDb.Models.Guilds", b =>
                {
                    b.Navigation("Captcha");

                    b.Navigation("Channels");

                    b.Navigation("Guilds_Captcha");

                    b.Navigation("Guilds_Meeting_Leave");

                    b.Navigation("Guilds_Meeting_Welcome");

                    b.Navigation("Guilds_Raid");

                    b.Navigation("Guilds_Warns");

                    b.Navigation("Reports");

                    b.Navigation("Role");

                    b.Navigation("Users_Guild");
                });

            modelBuilder.Entity("DarlingDb.Models.Pets", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("DarlingDb.Models.ReportSystem.Reports", b =>
                {
                    b.Navigation("ReportsList");
                });

            modelBuilder.Entity("DarlingDb.Models.Users", b =>
                {
                    b.Navigation("Boost");

                    b.Navigation("Feedback");

                    b.Navigation("Pet");

                    b.Navigation("Users_Guild");
                });

            modelBuilder.Entity("DarlingDb.Models.Users_Guild", b =>
                {
                    b.Navigation("Invites");

                    b.Navigation("PrivateChannels");

                    b.Navigation("Roles_Timer");

                    b.Navigation("TempUser");
                });

            modelBuilder.Entity("DarlingDb.Role", b =>
                {
                    b.Navigation("ButtonClick");

                    b.Navigation("EmoteClick");

                    b.Navigation("Guilds_Captcha");

                    b.Navigation("Guilds_Meeting_Welcome");

                    b.Navigation("Roles");

                    b.Navigation("Roles_Timer");
                });
#pragma warning restore 612, 618
        }
    }
}
